version: "3.7"
services:
    db:
        image: mysql:latest
        restart: always
        container_name: mysql_racedb_app
        command: --default-authentication-plugin=mysql_native_password
        env_file: ./dbconfig.env
        networks:
            racedb:
                aliases:
                    - database
        hostname: mysql_racedb_app
        volumes:
            - mysql-data:/var/lib/mysql

    racedb:
        image: mbuckaway/racedb-mysql:beta
        restart: always
        container_name: racedb_app
        ports:
            - "80:8000"
        env_file:
            - ./dbconfig.env
            - ./racedb.env
        environment:
            - sqlite3_database_fname:/racedb-data/RaceDB.sqlite3
            - PYTHONPATH:/RaceDB
            - RACEDBLOGFILE:/racedb-data/RaceDB-log.txt
        hostname: racedb_app
        networks:
            racedb:
                aliases:
                    - racedb
        depends_on:
            - db
        volumes:
            - racedb-data:/racedb-data
            - ./RaceDB.sqlite3:/RaceDB.sqlite3
volumes:
    mysql-data:
    racedb-data:

networks:
    racedb:

